### ISSUE TITLE
Not sure if function is yeilding consistent results

### ISSUE THREAD

**Issue by mikebyte00** [legiao/ea-hash#1]
Hi there,
Installed your package but I'm not sure I'm getting consistent results - I've scanned your code and it seems somewhat of an anomaly..
Could you hash 'graham' or 'mike' so I can see if our results match up?

Many thanks,
Mike

**Comment by tiagogoncalves89** [comment]
Hello Mike,

Thanks for reporting the issue.

I found a bug when cleaning the string, a new version is now available.

The hash for 'graham' is 'ed04e7de7106842af09a7c69bd72c4cc'
The hash for 'mike' is '9f9bde2cd83036ff6e9a8960304fe5aa' 

Best Regards,
Tiago

**Comment by mikebyte00** [comment]
Ah yes, thank you for the update. Works perfectly.
